# Purpose: Defines the target webserver hosts and their Ansible connection settings.
[webservers]
ens33 ansible_host=192.168.50.231 ansible_user=msu
ens33 ansible_host=192.168.50.183 ansible_user=msu

[webservers:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible
ansible_python_interpreter=/usr/bin/python3